int age = 25; // An integer variable
double height = 5.9; // A floating-point variable
String name = 'Rijwan';
String baseUrls = 'http// jhgsgsdhdkk';// base url at app constant
bool isStudent = true; // A boolean variable
var message = 'hello';
var number = '12'; //any type takes var
const double pi = 3.1213;
final currentTime = DateTime.now();
